PREFIX rr: <http://www.w3.org/ns/r2rml#>
PREFIX rml: <http://semweb.mmlab.be/ns/rml#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
INSERT DATA { 
    
    <epo:exampleclass2> a rr:TriplesMap;
                                        rml:logicalSource 
    [  rml:source "XXXX";
            rml:referenceFormulation "XXXX"];	   
      rr:subjectMap [
      rr:template "XXXX";
        rr:class <http://data.europa.eu/a4g/ontology#exampleclass2>];
    rr:predicateObjectMap [
        rr:predicate foaf:name;
        rr:objectMap[rr:template "https://exmampleuri/{valortabla}"]
	].
  }