PREFIX rr: <http://www.w3.org/ns/r2rml#>
PREFIX rml: <http://semweb.mmlab.be/ns/rml#>

INSERT DATA { 
    
    %TM_ID% a rr:TriplesMap;
    rml:logicalSource [  
        rml:source "XXXX";
        rml:referenceFormulation "XXXX"
    ];	   
    rr:subjectMap [
        rr:template "XXXX";
        rr:class %CLASS% 
    ] 
}