# Adds %DATA_PROPERTY% to %CLASS% with datatype %RANGE_DATA_PROPERTY% extracted from the range of %DATA_PROPERTY%. By defaylt, reference is used for the data.

PREFIX rr: <http://www.w3.org/ns/r2rml#>
PREFIX rml: <http://semweb.mmlab.be/ns/rml#>

INSERT { 
    ?triplesmap rr:predicateObjectMap [
        rr:predicate <%DATA_PROPERTY%>;
        rr:objectMap [
            rml:reference "XXXX";
            rr:datatype <%RANGE_DATA_PROPERTY%>
        ]
    ].
}
WHERE {
  	?triplesmap rr:subjectMap ?subjectMap .
    ?subjectMap rr:class <%CLASS%> .
}