# Adds %SUPERCLASS% to the %SUBCLASS%. This change triggers the second and third query, which add DATAPROPERTY and OBJECTPROPERTY where the domain is SUPERCLASS.

PREFIX rr: <http://www.w3.org/ns/r2rml#>

INSERT {  
    ?subjectMap rr:class <%SUPERCLASS%>.
}
WHERE {
    ?triplesmap rr:subjectMap ?subjectMap.
    ?subjectMap rr:class <%SUBCLASS%>.
}



# Adds %DATAPROPERTIES% where their domain are %SUPERCLASS%. This runs after the first query.
# Needs to be run for each DATAPROPERTY of %SUPERCLASS%
INSERT {  
    ?triplesmap rr:predicateObjectMap [
        rr:predicate <%DATAPROPERTY%>;
        rr:objectMap [
            rml:reference "XXXX";
            rr:datatype <%RANGE_DATAPROPERTY%>
        ]
    ].
}
WHERE {
    ?triplesmap rr:subjectMap ?subjectMap .
    ?subjectMap rr:class <%SUBCLASS%>, <%SUPERCLASS%> .
}


# Adds %OBJECTPROPERTY% where their domain are %SUPERCLASS% and the RANGE is %RANGECLASS%. This runs after the first query.
# Needs to be run for each OBJECTPROPERTY of %SUPERCLASS%
INSERT {  
    ?triplesmap rr:predicateObjectMap [
        rr:predicate <%OBJECTPROPERTY%>;
        rr:objectMap [
            rr:parentTriplesMap ?parent_tm;
            rr:joinCondition [
                rr:child "XXXX";
                rr:parent "XXXX"
            ]
        ]
    ].
}
WHERE {
    ?triplesmap rr:subjectMap ?subjectMap .
    ?subjectMap rr:class <%SUBCLASS%>, <%SUPERCLASS%> .

    ?parent_tm rr:subjectMap ?parent_subjectMap .
    ?parent_subjectMap rr:class <%RANGECLASS%> .
}