# Removes %DATAPROPERTY% from %CLASS. Extended version is also provided
PREFIX rr: <http://www.w3.org/ns/r2rml#>

DELETE { 
    ?triplesmap rr:predicateObjectMap ?pom.
    ?pom rr:predicate <%DATAPROPERTY%> . #if comes from the ontology, it's going to be always constant

    ?pom ?object_property ?objectMap. #either rr:objectMap or rr:object
    ?objectMap ?predicate_term ?objectValue . #removes everything under objectMap (including language, datatype or termType)
}
WHERE {
    ?triplesmap  rr:subjectMap ?subjectMap.
    ?subjectMap rr:class <%CLASS%>.

    ?triplesmap rr:predicateObjectMap ?pom.
   	?pom rr:predicate <%DATAPROPERTY%> . #if comes from the ontology, it's going to be always constant

    ?pom rr:objectMap|rr:object ?objectMap.
    ?objectMap ?predicate_term ?objectValue .
        
}

#Extended version where shortcuts are not used
DELETE { 
    ?triplesmap rr:predicateObjectMap ?pom.
    ?pom rr:predicateMap ?predicate . #if comes from the ontology, it's going to be always constant
    ?predicate rr:constant <%DATAPROPERTY%> .

    ?pom ?object_property ?objectMap. #either rr:objectMap or rr:object
    ?objectMap ?predicate_term ?objectValue . #removes everything under objectMap (including language, datatype or termType)
}
WHERE {
    ?triplesmap  rr:subjectMap ?subjectMap.
    ?subjectMap rr:class <%CLASS%>.

    ?triplesmap rr:predicateObjectMap ?pom.
    ?pom rr:predicateMap ?predicate . #if comes from the ontology, it's going to be always constant
    ?predicate rr:constant <%DATAPROPERTY%> .

    ?pom rr:objectMap|rr:object ?objectMap.
    ?objectMap ?predicate_term ?objectValue .
        
}