PREFIX rr: <http://www.w3.org/ns/r2rml#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
construct { 
    ?triplesmap a rr:TriplesMap.
	?triplesmap ?prop ?bnodesubject.
    ?triplesmap ?prop1 ?obj.
    ?obj ?prop2 ?obj1.
    ?bnodesubject rr:class <http://data.europa.eu/a4g/ontology#exampleclass1>.
    #PART OF THE QUERY To DELETE POM WHEN ITS CONTAINED IN TEMPLATE
    ?triplesmap rr:subjectMap ?bnodesub.
    ?bnodesub rr:template ?urisub.
    ?anothertriplesmap rr:predicateObjectMap ?pombnode.
    ?pombnode rr:objectMap ?omnode.
    ?omnode rr:template ?urisub.
    ?pombnode ?pomprop ?pomobj.
    #DELETION OF JOINS
    ?yetanothertriplesmap rr:predicateObjectMap ?pomnode1.
    ?pomnode1 rr:objectMap ?obnode1.
    ?obnode1 rr:parentTriplesMap ?triplesmap.
    ?pomnode1 ?a ?b.
	
}
    
 WHERE{ 
    ?triplesmap ?prop ?bnodesubject.
    ?triplesmap ?prop1 ?obj.
    ?obj ?prop2 ?obj1.
    ?bnodesubject rr:class <http://data.europa.eu/a4g/ontology#exampleclass1>. 
    #PART OF THE QUERY To DELETE POM WHEN ITS CONTAINED IN TEMPLATE
    OPTIONAL{
    ?triplesmap rr:subjectMap ?bnodesub.
    ?bnodesub rr:template ?urisub.
    ?anothertriplesmap rr:predicateObjectMap ?pombnode.
    ?pombnode rr:objectMap ?omnode.
    ?omnode rr:template ?urisub.
    ?pombnode ?pomprop ?pomobj.
    }
    #DELETION OF JOINS
    OPTIONAL{
    ?yetanothertriplesmap rr:predicateObjectMap ?pomnode1.
    ?pomnode1 rr:objectMap ?obnode1.
    ?obnode1 rr:parentTriplesMap ?triplesmap.
    ?pomnode1 ?a ?b.
    }
}