PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rr: <http://www.w3.org/ns/r2rml#>
#PREFIX rml: <http://w3id.org/rml/> (this will be the new one)
PREFIX rml: <http://semweb.mmlab.be/ns/rml#> # current one still in use
PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK {
    ?triples_map rdf:type rr:TriplesMap.
    ?triples_map rml:logicalSource ?logicalSource .
    ?logicalSource rml:source "XXXX" . #this is not wrong, are referneces to data that will be changed by the knowledge engineer manually
    ?logicalSource rml:referenceFormulation "XXXX" .
    ?triples_map rr:subjectMap ?subjectMap .
    ?subjectMap rr:class epo:ConcessionEstimate .
    ?subjectMap rr:template "XXXX"
}