 PREFIX sh: <http://www.w3.org/ns/shacl#> 
 INSERT { 
    ?propertyShape sh:sparql [ 
        a sh:SPARQLConstraint ; 
        sh:select "
            SELECT $this WHERE { 
                $this <http://myexampleuri.org/data#knows> ?v . 
                FILTER EXISTS { ?v <http://myexampleuri.org/data#knows> $this } 
            }" 
        ] 
} WHERE { 
    ?propertyShape sh:path <http://myexampleuri.org/data#knows> 
}